### In-class exercise for Tue, 2017-04-12.  If submitted by midnight, Thu, April 13th, you will earn 3 participation credits.

In [123]:
import numpy as np
import pandas as pd

## 1. Solve the following system of equations:

x1 + 2\*x2 = 7
-x2 + x3 = 6
x1 - 4\*x2 + x3 = -2

Use linear algebra (feel free to check your LA result with other methods if you have nothing better to do ;-) 


In [124]:
a = np.array([(1,2,0),(0,-1,1),(1,-4,1)])
b = np.array([7,6,-2])
x = np.linalg.solve(a,b)
x

array([ 1.,  3.,  9.])

## 2. Condition number
Read the AmesHousing dataset documentation.  It is sales price data for Ames, IA, the variable 'SalePrice' represents the sale price in USD.  We are working toward predicting the price based on the observed features.  (but we don't get that far...)

Determine the data type and import this data into python.  Ensure you imported it correctly.

In [145]:
housing_df = pd.read_csv('ameshousing.csv', sep = '\t')

2.1 The dataset includes a large number of variables.  Some of these are numeric (continuous), some are categoric (nominal) and others are ordered (ordinal).  However, many statistical methods can only handle numeric variables.

Look at variable 'Street'.  Is it numeric, categorical, or ordered?

In [85]:
type(housing_df['Street'][1])

str

The 'Street' variable's value is string type. So it is a categorical variable.

2.2 A standard approach to handle categorical variables is to create *dummies* out of these.  This can be achieved by 'pd.get_dummies()' function.  Transform 'Street' into dummies.  How many of these do you need in your calculations?

In [146]:
dum_df = pd.get_dummies(housing_df['Street'])
housing_df = housing_df.join(dum_df)

housing_df.head(10)

Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave   
1      2  526350040           20        RH          80.0     11622   Pave   
2      3  526351010           20        RL          81.0     14267   Pave   
3      4  526353030           20        RL          93.0     11160   Pave   
4      5  527105010           60        RL          74.0     13830   Pave   
5      6  527105030           60        RL          78.0      9978   Pave   
6      7  527127150          120        RL          41.0      4920   Pave   
7      8  527145080          120        RL          43.0      5005   Pave   
8      9  527146030          120        RL          39.0      5389   Pave   
9     10  527162130           60        RL          60.0      7500   Pave   

  Alley Lot Shape Land Contour  ...   Fence Misc Feature Misc Val Mo Sold  \
0   NaN       IR1          Lvl  ...     NaN          NaN        0       5   
1   NaN       Reg          Lvl  ...   MnPrv          NaN        0       6   
2   NaN       IR1          Lvl  ...     NaN         Gar2    12500       6   
3   NaN       Reg          Lvl  ...     NaN          NaN        0       4   
4   NaN       IR1          Lvl  ...   MnPrv          NaN        0       3   
5   NaN       IR1          Lvl  ...     NaN          NaN        0       6   
6   NaN       Reg          Lvl  ...     NaN          NaN        0       4   
7   NaN       IR1          HLS  ...     NaN          NaN        0       1   
8   NaN       IR1          Lvl  ...     NaN          NaN        0       3   
9   NaN       Reg          Lvl  ...     NaN          NaN        0       6   

  Yr Sold Sale Type Sale Condition SalePrice  Grvl  Pave  
0    2010       WD          Normal    215000     0     1  
1    2010       WD          Normal    105000     0     1  
2    2010       WD          Normal    172000     0     1  
3    2010       WD          Normal    244000     0     1  
4    2010       WD          Normal    189900     0     1  
5    2010       WD          Normal    195500     0     1  
6    2010       WD          Normal    213500     0     1  
7    2010       WD          Normal    191500     0     1  
8    2010       WD          Normal    236500     0     1  
9    2010       WD          Normal    189000     0     1  

[10 rows x 84 columns]

I need 2 dummies in the calculations.

2.3 The statistical methods typically require to be fed the *design matrix*, a matrix that includes only numeric vectors for each observation.  In case of categorical features, the design matrix will contain the corresponding rows of dummies.  Create the design matrix of the 'Street' variable.  You may use 'pd.DataFrame.as_matrix()' function.

In [147]:
street = pd.DataFrame.as_matrix(dum_df)
print(street[0:10,:])

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


2.4 Select another feature and add to the design matrix.  If you select a categorical one, it should be converted to dummies as above.  If it is numeric, you may take it as-is.  Ordered features may be transformed to ordered numbers (such as 1,2,3,4...).  Add the data from the new variable to your design matrix.  You may use 'numpy.hstack()' to concatenate matrices column-wise.


In [148]:
dum_df['SalePrice'] = housing_df['SalePrice']
new_matrix = pd.DataFrame.as_matrix(dum_df)
new_matrix

array([[     0,      1, 215000],
       [     0,      1, 105000],
       [     0,      1, 172000],
       ..., 
       [     0,      1, 132000],
       [     0,      1, 170000],
       [     0,      1, 188000]])

2.5 Is this matrix (near) singular?  Which variables (if any) cause
the singularity?  Proceed like this:
a) take the first column from your design matrix.  You will have nx1 matrix. 
b) compute the condition number of it  (you may use 'np.linalg.cond()').
c) print it
d) add the next column and proceed to b)

Now look how the condition number changes when you add the columns.  When it jump substantially, you have added a significant bit of multicollinearity into your design matrix.  However, condition numbers up to thousands is usually not a problem.


In [153]:
matrix_1 = new_matrix[:,0:1]
cond_1 = np.linalg.cond(matrix_1)
print("Condition number when adding 'Grvi' variable:" , cond_1)

matrix_2 = new_matrix[:,0:2]
cond_2 = np.linalg.cond(matrix_2)
print("Condition number when adding 'Pave' variable:" , cond_2)

matrix_3 = new_matrix[:,0:3]
cond_3 = np.linalg.cond(matrix_3)
print("Condition number when adding 'Sales Price' variable:" , cond_3)

Condition number when adding 'Grvi' variable: 1.0
Condition number when adding 'Pave' variable: 15.5938021876
Condition number when adding 'Sales Price' variable: 3100042.00479


Add 1-2 additional variables to your design matrix and repeat the process. 

In [150]:
dum_df['LotArea'] = housing_df['Lot Area']
dum_df['MoSold'] = housing_df['Mo Sold']
new_matrix1 = pd.DataFrame.as_matrix(dum_df)
new_matrix1

array([[     0,      1, 215000,  31770,      5],
       [     0,      1, 105000,  11622,      6],
       [     0,      1, 172000,  14267,      6],
       ..., 
       [     0,      1, 132000,  10441,      7],
       [     0,      1, 170000,  10010,      4],
       [     0,      1, 188000,   9627,     11]])

In [154]:
matrix_4 = new_matrix1[:,0:4]
cond_4 = np.linalg.cond(matrix_4)
print("Condition number when adding 'Lot Area' variable:" , cond_4)

matrix_5 = new_matrix1[:,0:5]
cond_5 = np.linalg.cond(matrix_5)
print("Condition number when adding 'Mo Sold' variable:" , cond_5)

Condition number when adding 'Lot Area' variable: 3166955.54374
Condition number when adding 'Mo Sold' variable: 3193060.21714
